# -*- coding: utf-8 -*-
"""Kris for.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pThzoN9PiMNyjUdVA6jv5LFc-IDWaflK
"""

listkota = ['jakarta','surabaya','depok','bekasi','solo','jogjakarta','semarang','makasar']
for i, kota in enumerate(listkota):
  print(i, kota)

## 0 sampai 4
for i in range(5):
  print("perulangan ke -", i)

## 10 sampai 15
for i in range(10, 16):
  print('i -', i)

## bilangan genap kelipatan 2
for i in range(2, 12, 2):
  print('i =', i)

## bilangan ganjil kelipatan 2
for bilangan_ganjil in range(1, 12, 2):
  print(bilangan_ganjil)

tuplebuah = ('Mangga', 'Jeruk', 'Apel', 'Pepaya')

for buah in tuplebuah:
  print(buah)

for karakter in "Indonesian":
  print(karakter)

for i in range(10, 20):
  # skip jika i == 15
  if (i == 15):
    continue

    print(i)

for i in range(10, 20):
  # hentikan jika i == 15
  if (i == 15):
    break

    print(i)

listkota = [
    'jakarta','Surabaya','Depok','Bekasi','Solo'
    ,'Jogjakarta','Semarang','Makassar'
]

for kota in listkota:
  print(kota)
else:
    print('Tidak ada lagi item yang tersisa')

listkota = [
    'Jakarta','Surabaya','Depok','Bekasi','Solo',
    'Jogjakarta','Semarang','Makassar'
]

KotaYangDicari = input('ketik nama kota yang kamu cari:')

for i, kota in enumerate(listkota):
  # kita ubah katanya ke lowercase agar
  # menjadi case insensitive
  if kota.lower() == kotaYangDicari.lower():
    print('kota yang anda cari berada pada indeks', i)
    break

  else:
    print('maaf, kota yang anda cari tidak ada')