# -*- coding: utf-8 -*-
"""Kristianbuku.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OBv4IirZd5Ch5s3YfqJ05z72Am_sh-S0
"""

# membuat fungsi
def salam():
  print ("hello, ini Kristian")

# pemanggilan fungsi
salam()
salam()
salam()

def salam(ucapan):
  print(ucapan)
salam("Selamat Siang Kristian")

def luas_segitiga(alas, tinggi):
  luas = (alas * tinggi) / 2
  print ("luas segitiga: %f" % luas)

luas_segitiga(5, 6)

# membuat variabel global
nama = "belajar kode"
versi = "1.0.0"

def help():
  # ini variabel lokal
  nama = "programku"
  versi = "1.0.1"

def help():
  nama = "programku"
  versi = "1.0.1"

print ("nama: %s" % nama)
  print ("versi: %s" % versi)

nama = "Kristian"
tanggal_lahir = "12 Juli 2003"
alamat = "keramat"
tempat_lahir = "desa ranggi asam"
jurusan = "ilmu komputer"
hobi = "fusal"

print ("nama: %s" % nama)
print ("tanggal_lahir: %s" % tanggal_lahir)
print ("tempat_lahir: %s" % tempat_lahir)
print ("alamat: %s" % alamat)
print ("jurusan: %s" % jurusan)
print ("hobi: %s" % hobi)

# fungsi untuk menampilkan semua data
def show():
  if len(buku) <= 0:
      print("BELUM ADA DATA")
  else:
      for indeks in range(len(buku)):
        print("[{}]] {}" .format(indeks, buku[indeks]))

def show():
  if len(buku) <= 0:
      print("BELUM ADA DATA")
  else:
      for indeks in range(len(buku)):
        print("[{}]] {}" .format(indeks, buku[indeks]))

def insert_data():
  buku_baru = input("judul buku: ")
  buku.append(buku_baru)

def edit_data():
  show_data()
  indeks = int(input("inputkan ID buku"))
  if indeks > len(buku):
    print("ID salah")
  else:
      judul_baru = input("judul baru: ")
      buku[indeks] = judul_baru

def delete_data():
  show_data()
  indeks = int(input("inputkan ID buku"))
  if indeks > len(buku):
    print("ID salah")
  else:
      buku.remove(buku[indeks])

def show_menu():
  print("\n")
  print("---------- MENU ----------")
  print("[1] show data")
  print("[2] insert data")
  print("[3] edit data")
  print("[4] delete data")
  print("[5] exit")

  menu = input("PILIH MENU> ")
  print("\n")

buku = []
def show_data():
    if len(buku) <= 0:
      print("belum ada data")
    else:
      for indek in range (len(buku)):
        print("[{}]] {}".format(indeks,buku[indeks]))

def insert_data():
    buku_baru = input("judul buku: ")
    buku.append(buku_baru)

def edit_data():
    show_data()
    indeks = int(input("inputkan ida buku"))
    if indeks > len(buku):
        print("id salah")
    else:
        judul_baru = input("judul baru:")
        buku[indeks] = judul_baru

def delete_data():
    show_data()
    indeks = int(input("inputkan ida buku"))
    if indeks > len(buku):
        print("id salah")
    else:
        buku.remove(buku[indeks])

def show_menu():
    print("\n")
    print("----------MENU----------")
    print("[1] show data")
    print("[2] insert data")
    print("[3] edit data")
    print("[4] delete data")
    print("[5] exit")

    menu = input("PILIH MENU")
    print("\n")

    if int(menu) == 1:
        show_data()
    elif int(menu) == 2:
        insert_data()
    elif int(menu) == 3:
        edit_data()
    elif int(menu) == 4:
        delete_data()
    elif int(menu) == 5:
        exit()
    else:
        print("salah pilih!")
if __name__ =="__main__":
      while True:
        show_menu()